from time import sleep
from selenium.webdriver import Chrome,ChromeOptions
o = ChromeOptions()
o.add_experimental_option("detach", True)
driver = Chrome(options=o)

driver.get("https://www.wikipedia.com")
driver.maximize_window()
driver.refresh()
print(driver.title)
print(driver.current_url)
driver.get('https://amazon.com')
sleep(5)
print(driver.title)
print(driver.current_url)
sleep(5)
driver.back()
sleep(5)
driver.forward()
driver.close()
